name: lint
description: Static analysis for sc4pac yaml metadata

inputs:
  path:
    description: Source folder containing yaml files to analyze
    required: true

runs:
  using: composite
  steps:
  - name: Install linter
    uses: memo33/sc4pac-actions/actions/setup-lint@main
  - name: Lint
    shell: bash
    run: |
      : Lint
      echo -e "\033[36;1m$(printf '%.s━' $(seq 1 80))\033[0m"  # horizontal line
      sc4pac-lint "$SRC_YAML"
    env:
      SRC_YAML: ${{ inputs.path }}
