name: setup
description: Set up sc4pac by downloading and installing the latest release

runs:
  using: composite
  steps:
  - name: Get latest sc4pac release
    id: get-release-info
    shell: bash
    working-directory: ${{ github.action_path }}
    run: |
      : Get latest sc4pac release
      SC4PAC_ZIP_URL="$(curl -s https://api.github.com/repos/memo33/sc4pac-tools/releases/latest | grep browser_download_url | cut -d '"' -f 4)"
      echo "url=$SC4PAC_ZIP_URL" >> $GITHUB_OUTPUT
      SC4PAC_VERSION="$(echo "$SC4PAC_ZIP_URL" | cut -d '/' -f 8)"
      echo "version=$SC4PAC_VERSION" >> $GITHUB_OUTPUT

  - uses: actions/cache@v4
    id: cache-sc4pac
    with:
      path: ${{ format('{0}/sc4pac-latest.zip', github.action_path) }}
      key: sc4pac-zip-${{ steps.get-release-info.outputs.version }}-${{ runner.os }}

  - name: Download sc4pac
    if: steps.cache-sc4pac.outputs.cache-hit != 'true'
    shell: bash
    working-directory: ${{ github.action_path }}
    run: |
      : Download sc4pac
      curl -s -L "$SC4PAC_ZIP_URL" > sc4pac-latest.zip
    env:
      SC4PAC_ZIP_URL: ${{ steps.get-release-info.outputs.url }}

  - name: Install sc4pac
    shell: bash
    working-directory: ${{ github.action_path }}
    run: |
      : Install sc4pac
      sudo unzip -q -d /usr/local/lib/sc4pac sc4pac-latest.zip
      sudo ln -s /usr/local/lib/sc4pac/sc4pac /usr/local/bin/sc4pac
      echo "Installed sc4pac version: $SC4PAC_VERSION"
    env:
      SC4PAC_VERSION: ${{ steps.get-release-info.outputs.version }}
