name: setup
description: Set up sc4pac by download and installing the latest release

runs:
  using: composite
  steps:
  - name: Install sc4pac
    shell: bash
    working-directory: ${{ github.action_path }}
    run: |
      : Install sc4pac
      # download and extract latest sc4pac CLI
      SC4PAC_ZIP_URL="$(curl -s https://api.github.com/repos/memo33/sc4pac-tools/releases/latest | grep browser_download_url | cut -d '"' -f 4)"
      curl -s -L "$SC4PAC_ZIP_URL" > sc4pac-latest.zip
      sudo unzip -q -d /usr/local/lib/sc4pac sc4pac-latest.zip
      rm -f sc4pac-latest.zip
      sudo ln -s /usr/local/lib/sc4pac/sc4pac /usr/local/bin/sc4pac
      echo "Installed sc4pac version: $(sc4pac --version)"
